
package src.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http:/service.tomtone.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param lpszUser
     * @param lpszPswd
     * @param bStyleXml
     * @param lpszNetwk
     * @return
     *     returns com.MatrixResult
     */
    @WebMethod(operationName = "InvokeLogin", action = "http:/service.tomtone.com/InvokeLogin")
    @WebResult(name = "InvokeLoginResult", targetNamespace = "http:/service.tomtone.com/")
    @RequestWrapper(localName = "InvokeLogin", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeLogin")
    @ResponseWrapper(localName = "InvokeLoginResponse", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeLoginResponse")
    public MatrixResult invokeLogin(
        @WebParam(name = "lpszUser", targetNamespace = "http:/service.tomtone.com/")
        String lpszUser,
        @WebParam(name = "lpszPswd", targetNamespace = "http:/service.tomtone.com/")
        String lpszPswd,
        @WebParam(name = "lpszNetwk", targetNamespace = "http:/service.tomtone.com/")
        String lpszNetwk,
        @WebParam(name = "bStyleXml", targetNamespace = "http:/service.tomtone.com/")
        int bStyleXml);

    /**
     * 
     * @param bStyleXml
     * @param lpszToken
     * @return
     *     returns com.MatrixResult
     */
    @WebMethod(operationName = "InvokeLogout", action = "http:/service.tomtone.com/InvokeLogout")
    @WebResult(name = "InvokeLogoutResult", targetNamespace = "http:/service.tomtone.com/")
    @RequestWrapper(localName = "InvokeLogout", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeLogout")
    @ResponseWrapper(localName = "InvokeLogoutResponse", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeLogoutResponse")
    public MatrixResult invokeLogout(
        @WebParam(name = "lpszToken", targetNamespace = "http:/service.tomtone.com/")
        String lpszToken,
        @WebParam(name = "bStyleXml", targetNamespace = "http:/service.tomtone.com/")
        int bStyleXml);

    /**
     * 
     * @param lpszHelper
     * @param bStyleXml
     * @param lpszToken
     * @return
     *     returns com.MatrixResult
     */
    @WebMethod(operationName = "InvokeManual", action = "http:/service.tomtone.com/InvokeManual")
    @WebResult(name = "InvokeManualResult", targetNamespace = "http:/service.tomtone.com/")
    @RequestWrapper(localName = "InvokeManual", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeManual")
    @ResponseWrapper(localName = "InvokeManualResponse", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeManualResponse")
    public MatrixResult invokeManual(
        @WebParam(name = "lpszToken", targetNamespace = "http:/service.tomtone.com/")
        String lpszToken,
        @WebParam(name = "lpszHelper", targetNamespace = "http:/service.tomtone.com/")
        String lpszHelper,
        @WebParam(name = "bStyleXml", targetNamespace = "http:/service.tomtone.com/")
        int bStyleXml);

    /**
     * 
     * @param lpszHelper
     * @param lpszKey
     * @param lpszParams
     * @param bStyleXml
     * @param lpszToken
     * @return
     *     returns com.MatrixResult
     */
    @WebMethod(operationName = "InvokeHelper", action = "http:/service.tomtone.com/InvokeHelper")
    @WebResult(name = "InvokeHelperResult", targetNamespace = "http:/service.tomtone.com/")
    @RequestWrapper(localName = "InvokeHelper", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeHelper")
    @ResponseWrapper(localName = "InvokeHelperResponse", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeHelperResponse")
    public MatrixResult invokeHelper(
        @WebParam(name = "lpszToken", targetNamespace = "http:/service.tomtone.com/")
        String lpszToken,
        @WebParam(name = "lpszHelper", targetNamespace = "http:/service.tomtone.com/")
        String lpszHelper,
        @WebParam(name = "lpszKey", targetNamespace = "http:/service.tomtone.com/")
        String lpszKey,
        @WebParam(name = "lpszParams", targetNamespace = "http:/service.tomtone.com/")
        String lpszParams,
        @WebParam(name = "bStyleXml", targetNamespace = "http:/service.tomtone.com/")
        int bStyleXml);

    /**
     * 
     * @param lpszHelper
     * @param lpszKey
     * @param lpszParams
     * @param bStyleXml
     * @param lpszToken
     * @return
     *     returns com.MatrixResult
     */
    @WebMethod(operationName = "InvokeScript", action = "http:/service.tomtone.com/InvokeScript")
    @WebResult(name = "InvokeScriptResult", targetNamespace = "http:/service.tomtone.com/")
    @RequestWrapper(localName = "InvokeScript", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeScript")
    @ResponseWrapper(localName = "InvokeScriptResponse", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeScriptResponse")
    public MatrixResult invokeScript(
        @WebParam(name = "lpszToken", targetNamespace = "http:/service.tomtone.com/")
        String lpszToken,
        @WebParam(name = "lpszHelper", targetNamespace = "http:/service.tomtone.com/")
        String lpszHelper,
        @WebParam(name = "lpszKey", targetNamespace = "http:/service.tomtone.com/")
        String lpszKey,
        @WebParam(name = "lpszParams", targetNamespace = "http:/service.tomtone.com/")
        String lpszParams,
        @WebParam(name = "bStyleXml", targetNamespace = "http:/service.tomtone.com/")
        int bStyleXml);

    /**
     * 
     * @param lpszUrl
     * @param bPost
     * @param lpszParams
     * @param bUtf8
     * @return
     *     returns com.MatrixResult
     */
    @WebMethod(operationName = "InvokeRequest", action = "http:/service.tomtone.com/InvokeRequest")
    @WebResult(name = "InvokeRequestResult", targetNamespace = "http:/service.tomtone.com/")
    @RequestWrapper(localName = "InvokeRequest", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeRequest")
    @ResponseWrapper(localName = "InvokeRequestResponse", targetNamespace = "http:/service.tomtone.com/", className = "com.InvokeRequestResponse")
    public MatrixResult invokeRequest(
        @WebParam(name = "lpszUrl", targetNamespace = "http:/service.tomtone.com/")
        String lpszUrl,
        @WebParam(name = "lpszParams", targetNamespace = "http:/service.tomtone.com/")
        String lpszParams,
        @WebParam(name = "bPost", targetNamespace = "http:/service.tomtone.com/")
        boolean bPost,
        @WebParam(name = "bUtf8", targetNamespace = "http:/service.tomtone.com/")
        boolean bUtf8);

}
